# https://prettier.io/docs/en/configuration.html
arrowParens: avoid
endOfLine: lf
trailingComma: none
tabWidth: 2
plugins: ['@shopify/prettier-plugin-liquid']
semi: true
singleQuote: true
overrides:
  - files:
      - ./course/_includes/*.html
      - ./course/_layouts/*.html
    options:
      parser: liquid-html
