name: archidep

services:
  rp:
    image: 'traefik:v3.5'
    container_name: 'traefik'
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entryPoints.web.address=:80'
    depends_on:
      - assets-server
    ports:
      - '42000:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  assets-server:
    image: archidep/assets-server:latest
    build:
      context: .
      target: assets-server
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.archidep-assets.rule=Host(`localhost`) && (Path(`/`) || PathPrefix(`/assets/`) || PathPrefix(`/course/`) || PathRegexp(`^/[^/]+\\.[^/]+$`))"
      - 'traefik.http.routers.archidep-assets.entrypoints=web'
      - 'traefik.http.services.archidep-assets.loadbalancer.server.port=80'
    restart: unless-stopped

  app:
    image: archidep/website:latest
    build:
      context: .
      target: app
    depends_on:
      - db
    environment:
      ARCHIDEP_AUTH_SWITCH_EDU_ID_CLIENT_ID:
      ARCHIDEP_AUTH_SWITCH_EDU_ID_CLIENT_SECRET:
      ARCHIDEP_AUTH_SWITCH_EDU_ID_ROOT_USERS:
      ARCHIDEP_REPO_URL:
      ARCHIDEP_WEB_ENDPOINT_HTTP_IP:
      ARCHIDEP_WEB_ENDPOINT_HTTP_PORT:
      ARCHIDEP_WEB_ENDPOINT_LIVE_VIEW_SIGNING_SALT:
      ARCHIDEP_WEB_ENDPOINT_SECRET_KEY_BASE:
      ARCHIDEP_WEB_ENDPOINT_SESSION_SIGNING_SALT:
      ARCHIDEP_WEB_ENDPOINT_UPLOADS_DIRECTORY: /var/lib/app/uploads
      ARCHIDEP_WEB_ENDPOINT_URL:
    init: true
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.archidep-app.rule=Host(`localhost`) && !Path(`/`) && !PathPrefix(`/assets/`) && !PathPrefix(`/course/`) && !PathRegexp(`^/[^/]+\\.[^/]+$`)"
      - 'traefik.http.routers.archidep-app.entrypoints=web'
      - 'traefik.http.services.archidep-app.loadbalancer.server.port=42000'
    restart: unless-stopped
    volumes:
      - app_uploads:/var/lib/app/uploads:rw

  db:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: archidep
      POSTGRES_PASSWORD: '${ARCHIDEP_DATABASE_PASSWORD}'
      POSTGRES_USER: archidep
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  app_uploads:
  db_data:
