name: archidep-dev

services:
  app:
    image: archidep/dev-app
    build:
      context: .
      dockerfile: ./docker/dev/app/Dockerfile
    depends_on:
      app-assets:
        condition: service_healthy
        restart: true
      course:
        condition: service_healthy
        restart: true
      course-assets:
        condition: service_healthy
        restart: true
      db:
        condition: service_healthy
        restart: true
      theme:
        condition: service_healthy
        restart: true
    environment:
      ARCHIDEP_AUTH_SWITCH_EDU_ID_CLIENT_ID:
      ARCHIDEP_AUTH_SWITCH_EDU_ID_CLIENT_SECRET:
      ARCHIDEP_AUTH_SWITCH_EDU_ID_ROOT_USERS:
      ARCHIDEP_GIT_CWD: /var/lib/archidep/git
      ARCHIDEP_REPO_URL: ecto://archidep:archidep@db:5432/archidep
      ARCHIDEP_SERVERS_SSH_PRIVATE_KEY_FILE: '/etc/archidep/ssh/id_${ARCHIDEP_SERVERS_SSH_PRIVATE_KEY_FILE_TYPE}'
      ARCHIDEP_SERVERS_SSH_PUBLIC_KEY:
      ARCHIDEP_WEB_ENDPOINT_HTTP_IP: 0.0.0.0
      ARCHIDEP_WEB_ENDPOINT_HTTP_PORT: 42000
      ARCHIDEP_WEB_ENDPOINT_LIVE_VIEW_SIGNING_SALT:
      ARCHIDEP_WEB_ENDPOINT_SECRET_KEY_BASE:
      ARCHIDEP_WEB_ENDPOINT_SESSION_SIGNING_SALT:
      ARCHIDEP_WEB_ENDPOINT_UPLOADS_DIRECTORY: /var/lib/archidep/uploads
      ARCHIDEP_WEB_ENDPOINT_URL: http://localhost:42000
      MIX_BUILD_PATH: /var/lib/archidep/build
      MIX_DEPS_PATH: /var/lib/archidep/deps
    init: true
    ports:
      - '127.0.0.1:42000:42000'
      - '127.0.0.1:42003:42003'
    volumes:
      - ./app/assets:/archidep/app/assets:ro
      - ./app/config/config.exs:/archidep/app/config/config.exs:ro
      - ./app/config/dev.exs:/archidep/app/config/dev.exs:ro
      - ./app/config/prod.exs:/archidep/app/config/prod.exs:ro
      - ./app/config/runtime.exs:/archidep/app/config/runtime.exs:ro
      - ./app/config/test.exs:/archidep/app/config/test.exs:ro
      - ./app/.credo.exs:/archidep/app/.credo.exs:ro
      - ./app/.formatter.exs:/archidep/app/.formatter.exs:ro
      - ./app/mix.exs:/archidep/app/mix.exs:ro
      - ./app/mix.lock:/archidep/app/mix.lock:ro
      - ./app/lib:/archidep/app/lib:ro
      - ./app/priv/ansible:/archidep/app/priv/ansible:ro
      - ./app/priv/gettext:/archidep/app/priv/gettext:ro
      - ./app/priv/repo:/archidep/app/priv/repo:ro
      - ./app/priv/scripts:/archidep/app/priv/scripts:ro
      - ./app/priv/ssh/id_${ARCHIDEP_SERVERS_SSH_PRIVATE_KEY_FILE_TYPE}:/etc/archidep/ssh/id_${ARCHIDEP_SERVERS_SSH_PRIVATE_KEY_FILE_TYPE}:ro
      - ./app/priv/ssh/id_${ARCHIDEP_SERVERS_SSH_PRIVATE_KEY_FILE_TYPE}.pub:/etc/archidep/ssh/id_${ARCHIDEP_SERVERS_SSH_PRIVATE_KEY_FILE_TYPE}.pub:ro
      - ./app/test:/archidep/app/test:ro
      - ./.git:/var/lib/archidep/git/.git:ro
      - ./tmp/docker/dev/app/build:/var/lib/archidep/build:rw
      - ./tmp/docker/dev/app/deps:/var/lib/archidep/deps:rw
      - ./tmp/docker/dev/app/mix:/home/archidep/.mix:rw
      - ./tmp/docker/dev/app/priv/static:/archidep/app/priv/static:rw
      - ./tmp/docker/dev/app/uploads:/var/lib/archidep/uploads:rw

  app-assets:
    image: archidep/dev-app-assets
    build:
      context: .
      dockerfile: ./docker/dev/app-assets/Dockerfile
    volumes:
      - ./app/assets:/archidep/app/assets:ro
      - ./app/package.json:/archidep/app/package.json:ro
      - ./package.json:/archidep/package.json:ro
      - ./package-lock.json:/archidep/package-lock.json:ro
      - ./tmp/docker/dev/app/deps:/archidep/app/deps:ro
      - ./tmp/docker/dev/app/priv:/archidep/app/priv:rw
      - ./tmp/docker/dev/node/dist/node_modules:/archidep/node_modules:ro

  course:
    image: archidep/dev-course
    build:
      context: .
      dockerfile: ./docker/dev/course/Dockerfile
    depends_on:
      app-assets:
        condition: service_healthy
        restart: true
      course-assets:
        condition: service_healthy
        restart: true
      theme:
        condition: service_healthy
        restart: true
    ports:
      - '127.0.0.1:42002:42002'
    volumes:
      - ./app/mix.exs:/archidep/app/mix.exs:ro
      - ./course:/archidep/course:ro
      - ./package.json:/archidep/package.json:ro
      - ./package-lock.json:/archidep/package-lock.json:ro
      - ./tmp/docker/dev/app/priv:/archidep/app/priv:rw
      - ./tmp/docker/dev/course/bundle:/var/lib/archidep/bundle:rw
      - ./tmp/docker/dev/node/dist/node_modules:/archidep/node_modules:ro

  course-assets:
    image: archidep/dev-course-assets
    build:
      context: .
      dockerfile: ./docker/dev/course-assets/Dockerfile
    volumes:
      - ./course:/archidep/course:ro
      - ./package.json:/archidep/package.json:ro
      - ./package-lock.json:/archidep/package-lock.json:ro
      - ./tmp/docker/dev/app/priv:/archidep/app/priv:rw
      - ./tmp/docker/dev/node/dist/node_modules:/archidep/node_modules:ro

  node:
    image: archidep/dev-node
    build:
      context: .
      dockerfile: ./docker/dev/node/Dockerfile
    volumes:
      - ./app/package.json:/etc/archidep/app/package.json:ro
      - ./course/package.json:/etc/archidep/course/package.json:ro
      - ./package.json:/etc/archidep/package.json:ro
      - ./package-lock.json:/etc/archidep/package-lock.json:ro
      - ./theme/package.json:/etc/archidep/theme/package.json:ro
      - ./tmp/docker/dev/node/dist:/archidep:rw
      - ./tmp/docker/dev/node/npm:/home/archidep/.npm:rw

  ssh:
    image: archidep/dev-ssh
    build:
      context: .
      dockerfile: ./docker/dev/ssh/Dockerfile
    volumes:
      - ./app/priv/ssh:/home/archidep/.ssh:rw

  theme:
    image: archidep/dev-theme
    build:
      context: .
      dockerfile: ./docker/dev/theme/Dockerfile
    volumes:
      - ./app/lib:/archidep/app/lib:ro
      - ./course:/archidep/course:ro
      - ./theme:/archidep/theme:ro
      - ./package.json:/archidep/package.json:ro
      - ./package-lock.json:/archidep/package-lock.json:ro
      - ./tmp/docker/dev/app/deps:/archidep/app/deps:ro
      - ./tmp/docker/dev/app/priv:/archidep/app/priv:rw
      - ./tmp/docker/dev/node/dist/node_modules:/archidep/node_modules:ro

  db:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: archidep
      POSTGRES_PASSWORD: archidep
      POSTGRES_USER: archidep
    healthcheck:
      test: ['CMD', 'pg_isready', '--dbname=archidep', '--username=archidep']
      interval: 5s
      timeout: 10s
      retries: 6
      start_period: 30s
      start_interval: 5s
    volumes:
      - ./tmp/docker/dev/db/data:/var/lib/postgresql/data:rw
