defmodule Mix.Tasks.Theme.HighlightCss do
  @shortdoc "Generate the theme's syntax highlighting stylesheets"

  @moduledoc """
  Write `theme/src/highlight-light.css` and `theme/src/highlight-dark.css` from
  the [Lumis](https://hexdocs.pm/lumis) themes the course material's code blocks
  are coloured with.

  The two files are one rule per token class of a colour scheme, a few hundred
  of them, so they are generated rather than written by hand. Run this task
  after changing either theme below and after upgrading Lumis.

  The dark stylesheet is the same CSS inside a `prefers-color-scheme` query,
  which is how the rest of the theme follows the system colour scheme.

  Options:

  - `--output` — the directory to write the two stylesheets in. Defaults to the
    theme's own `src`, which is where the theme's build reads them from.
  """

  use Mix.Task

  @light_theme "solarized_autumn_light"
  @dark_theme "solarized_autumn_dark"

  @source_directory Path.expand("../../../../../theme/src", __DIR__)

  @requirements ["app.config"]

  @impl Mix.Task
  @spec run(term()) :: :ok
  def run(args) do
    {opts, [], []} = OptionParser.parse(args, strict: [output: :string])
    dir = Keyword.get(opts, :output, @source_directory)

    write(dir, "highlight-light.css", Lumis.Theme.build_css!(@light_theme))
    write(dir, "highlight-dark.css", dark(Lumis.Theme.build_css!(@dark_theme)))
  end

  defp dark(css) do
    indented =
      css
      |> String.split("\n")
      |> Enum.map_join("\n", fn
        "" -> ""
        line -> "  " <> line
      end)

    "@media (prefers-color-scheme: dark) {\n#{indented}}\n"
  end

  defp write(dir, file, css) do
    path = Path.join(dir, file)
    File.mkdir_p!(dir)
    File.write!(path, "/* Generated by `mix theme.highlight_css`. */\n" <> css)
    Mix.shell().info("Wrote #{path}")
  end
end
