import Config

config :archidep, ArchiDepWeb.Endpoint,
  http: [
    # See the documentation on https://hexdocs.pm/bandit/Bandit.html#t:options/0
    # for details about using IPv6 vs IPv4 and loopback vs public addresses.
    ip: {0, 0, 0, 0}
  ],
  # Path to a cache manifest containing the digested version of static files.
  # This manifest is generated by the `mix assets.deploy` task, which you should
  # run after static files are built and before starting your production server.
  cache_static_manifest: "priv/static/cache_manifest.json",
  # The unprefixed "/assets" path, which the reverse proxy sends here rather
  # than to the static server in front of the course material site. Only the
  # dashboard asks for it: a page of a build references its own edition's copy,
  # under that edition's prefix. The static server holding it as well would mean
  # either carrying the whole digested tree a second time or symlinking one
  # edition's copy to the root, which is what teaches an image which edition it
  # is serving.
  serve_static: true

# Where the finished editions are kept, which the static server in front of the
# course material site serves as a second root and this application only reads:
# it holds none of these bytes out, and mounts them to be able to say whether
# the deployment is complete.
config :archidep, course_site: [archives_dir: "/var/lib/archidep/archives"]

# Enable Prometheus metrics server
config :archidep, ArchiDep.PromEx, disabled: false, metrics_server: [port: 42003]

# Swoosh API Client
config :swoosh,
  api_client: Swoosh.ApiClient.Finch,
  finch_name: ArchiDep.Finch,
  # Disable Swoosh Local Memory Storage
  local: false

config :ueberauth_oidcc, :issuers, [
  %{name: :switch_edu_id, issuer: "https://login.eduid.ch/"}
]

# Runtime production configuration, including reading of environment variables,
# is done on config/runtime.exs.
