import Config

config :archidep, ArchiDepWeb.Endpoint,
  http: [
    # See the documentation on https://hexdocs.pm/bandit/Bandit.html#t:options/0
    # for details about using IPv6 vs IPv4 and loopback vs public addresses.
    ip: {0, 0, 0, 0}
  ],
  # Path to a cache manifest containing the digested version of static files.
  # This manifest is generated by the `mix assets.deploy` task, which you should
  # run after static files are built and before starting your production server.
  cache_static_manifest: "priv/static/cache_manifest.json"

# Enable Prometheus metrics server
config :archidep, ArchiDep.PromEx, disabled: false, metrics_server: [port: 42003]

# Swoosh API Client
config :swoosh,
  api_client: Swoosh.ApiClient.Finch,
  finch_name: ArchiDep.Finch,
  # Disable Swoosh Local Memory Storage
  local: false

# Runtime production configuration, including reading of environment variables,
# is done on config/runtime.exs.
