defmodule ArchiDep.CourseSite.Urls.PdfManifest do
  @moduledoc """
  Where the generated PDFs of a build are published, and what they are called.

  The PDFs of the slides and the cheatsheets are generated by a step of its own
  and published either alongside the site or somewhere else entirely, so that
  the server does not have to store them. What each one is called follows from
  the page it is of (`ArchiDep.CourseSite.Build.PdfNames`); where they are
  published is the deployment fact this manifest carries, as a base:

  - `:site` — published under the build's own prefix, at `/pdf/<name>`.
  - `{:external, base}` — published under an absolute base URL, e.g. a bucket or
    a release.

  An entry is normally the PDF's path under that base. A host that renames what
  it is given (a GitHub release turns spaces into periods, for instance) makes
  the URL impossible to derive from the local name, so an entry may instead be a
  `{:url, url}` override that is used verbatim.
  """

  alias ArchiDep.CourseSite.PageRef

  @enforce_keys [:base]
  defstruct base: nil, entries: %{}

  @type base :: :site | {:external, String.t()}
  @type entry :: String.t() | {:url, String.t()}

  @type t :: %__MODULE__{
          base: base(),
          entries: %{PageRef.t() => entry()}
        }

  @doc """
  Build a PDF manifest from page references to the name of each page's PDF under
  the given base, or to a full URL overriding it.
  """
  @spec new(base(), %{PageRef.t() => entry()}) :: t()
  def new(base, entries) when is_map(entries),
    do: %__MODULE__{base: validate_base!(base), entries: entries}

  @doc """
  Look up the PDF of a page.

      iex> manifest = PdfManifest.new(:site, %{{:cheatsheet, "git"} => "archidep-999-git.pdf"})
      iex> PdfManifest.fetch(manifest, {:cheatsheet, "git"})
      {:ok, "archidep-999-git.pdf"}

      iex> PdfManifest.fetch(PdfManifest.new(:site, %{}), {:cheatsheet, "git"})
      :error
  """
  @spec fetch(t(), PageRef.t()) :: {:ok, entry()} | :error
  def fetch(%__MODULE__{entries: entries}, page), do: Map.fetch(entries, page)

  @doc """
  Check where a build publishes its PDFs, handing the base back and raising an
  `ArgumentError` when it is malformed.

  Public so that whoever states a base — a build task, the development watcher,
  the step that publishes them — is told of a typo where it was written, rather
  than after a whole course has been read.

      iex> PdfManifest.validate_base!({:external, "https://example.com/pdf/2026"})
      {:external, "https://example.com/pdf/2026"}

      iex> PdfManifest.validate_base!({:external, "example.com/pdf"})
      ** (ArgumentError) PDF base URL "example.com/pdf" must be an absolute URL
  """
  @spec validate_base!(term()) :: base()
  def validate_base!(:site), do: :site

  def validate_base!({:external, base} = publication) when is_binary(base) do
    cond do
      not String.starts_with?(base, ["http://", "https://"]) ->
        raise ArgumentError, "PDF base URL #{inspect(base)} must be an absolute URL"

      String.ends_with?(base, "/") ->
        raise ArgumentError, "PDF base URL #{inspect(base)} must not end with a slash"

      true ->
        publication
    end
  end

  def validate_base!(base),
    do: raise(ArgumentError, "Invalid PDF publication base #{inspect(base)}")
end
