defmodule ArchiDep.CourseSite.Urls.PdfManifest do
  @moduledoc """
  Where the generated PDFs of a build are published, and what they are called.

  The PDFs of the slides and the cheatsheets are generated by a separate,
  human-run step and published either alongside the site or somewhere else
  entirely, so that the server does not have to store them. Both are the same
  manifest with a different base:

  - `:site` — published under the build's own prefix, at `/pdf/<name>`.
  - `{:external, base}` — published under an absolute base URL, e.g. a bucket or
    a release.

  An entry is normally the PDF's path under that base. A host that renames what
  it is given (a GitHub release turns spaces into periods, for instance) makes
  the URL impossible to derive from the local name, so an entry may instead be a
  `{:url, url}` override that is used verbatim.
  """

  alias ArchiDep.CourseSite.PageRef

  @enforce_keys [:base]
  defstruct base: nil, entries: %{}

  @type base :: :site | {:external, String.t()}
  @type entry :: String.t() | {:url, String.t()}

  @type t :: %__MODULE__{
          base: base(),
          entries: %{PageRef.t() => entry()}
        }

  @doc """
  Build a PDF manifest from page references to the name of each page's PDF under
  the given base, or to a full URL overriding it.
  """
  @spec new(base(), %{PageRef.t() => entry()}) :: t()
  def new(base, entries) when is_map(entries) do
    validate_base!(base)
    %__MODULE__{base: base, entries: entries}
  end

  @doc """
  Look up the PDF of a page.

      iex> manifest = PdfManifest.new(:site, %{{:cheatsheet, "git"} => "ArchiDep 999 - Git.pdf"})
      iex> PdfManifest.fetch(manifest, {:cheatsheet, "git"})
      {:ok, "ArchiDep 999 - Git.pdf"}

      iex> PdfManifest.fetch(PdfManifest.new(:site, %{}), {:cheatsheet, "git"})
      :error
  """
  @spec fetch(t(), PageRef.t()) :: {:ok, entry()} | :error
  def fetch(%__MODULE__{entries: entries}, page), do: Map.fetch(entries, page)

  defp validate_base!(:site), do: :ok

  defp validate_base!({:external, base}) when is_binary(base) do
    if String.ends_with?(base, "/") do
      raise ArgumentError,
            "PDF base URL #{inspect(base)} must not end with a slash"
    end

    :ok
  end

  defp validate_base!(base),
    do: raise(ArgumentError, "Invalid PDF publication base #{inspect(base)}")
end
