defmodule Mix.Tasks.Theme.HighlightCssTest do
  # `Mix.shell/0` is global to the VM.
  use ExUnit.Case, async: false

  import ArchiDep.Support.MixTaskTestHelpers

  alias Mix.Tasks.Theme.HighlightCss

  @moduletag :tmp_dir

  @generated "/* Generated by `mix theme.highlight_css`. */\n"

  setup :capture_mix_shell

  describe "run/1" do
    test "writes the light stylesheet as the theme's own CSS", %{tmp_dir: tmp_dir} do
      output_dir = Path.join(tmp_dir, "src")

      HighlightCss.run(["--output", output_dir])

      assert File.read!(Path.join(output_dir, "highlight-light.css")) ==
               @generated <> Lumis.Theme.build_css!("solarized_autumn_light")
    end

    test "writes the dark stylesheet inside a prefers-color-scheme query",
         %{tmp_dir: tmp_dir} do
      output_dir = Path.join(tmp_dir, "src")

      HighlightCss.run(["--output", output_dir])

      indented =
        "solarized_autumn_dark"
        |> Lumis.Theme.build_css!()
        |> String.split("\n")
        |> Enum.map_join("\n", fn
          "" -> ""
          line -> "  " <> line
        end)

      assert File.read!(Path.join(output_dir, "highlight-dark.css")) ==
               @generated <> "@media (prefers-color-scheme: dark) {\n" <> indented <> "}\n"
    end

    test "names both files it wrote", %{tmp_dir: tmp_dir} do
      output_dir = Path.join(tmp_dir, "src")

      HighlightCss.run(["--output", output_dir])

      assert shell_output() == [
               {:info, "Wrote #{Path.join(output_dir, "highlight-light.css")}"},
               {:info, "Wrote #{Path.join(output_dir, "highlight-dark.css")}"}
             ]
    end
  end
end
