---
- name: Install Docker dependencies
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - ca-certificates
    - curl
    - gnupg
  become: true
  tags: [docker, install]

- name: Create Docker configuration directory
  file:
    path: /etc/docker
    owner: root
    group: root
    mode: 0700
    state: directory
  become: true
  tags: [docker, install]

- name: Set up Docker daemon initial configuration
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  become: true
  tags: [docker, config]

- name: Add Docker APT repository key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
  become: true
  register: docker_apt_key
  tags: [docker, install]

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  become: true
  register: docker_apt_repository
  tags: [docker, install]

- name: Update APT cache
  apt:
    update_cache: yes
  become: true
  when: docker_apt_key is changed or docker_apt_repository is changed
  tags: [docker, install]

- name: Install Docker
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - containerd.io
    - docker-buildx-plugin
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
  become: true
  tags: [docker, install]

- name: Make sure Docker works
  command: docker run --rm hello-world
  changed_when: false
  become: true
  tags: [docker]
