export const loadingMessages = [
  // Generic/computer
  'Reticulating splines',
  'Lifting weights',
  'Pushing pixels',
  'Formulating plan',
  'Feeding developers',
  'Adjusting power level',
  'Accelerating disks',
  'Calibrating positions',
  'Shedding core',
  'Increasing power',
  'Checking sensors',
  'Connecting bus',
  'Inverting ports',
  'Bypassing capacitor',
  'Reversing bandwidth',
  'Virtualizing microchip',
  'Synthesizing drivers',
  'Parsing system',
  'Navigating arrays',
  'Overflowing stack',
  'Compiling binaries',
  'Compressing data',
  'Leaking memory',
  'Jiggling internet',
  'Ejecting floppy',
  'Testing processor',
  'Rounding integers',
  'Inverting transponders',
  'Bypassing silicon',
  'Pumping gas',
  'Emptying pipes',
  'Completing geometry',
  'Benching wattage',
  'Automating processes',
  'Defragging hard drive',
  'Upgrading RAM',
  'Rendering polygons',
  'Patching vulnerabilities',
  'Decrypting mainframe',
  'Rolling drivers',
  'Mining for bitcoins',
  'Recompiling kernel',
  'Polishing CPUs',
  // Philosophy
  'Questioning identity',
  'Pondering existence',
  'Contemplating reality',
  'Questioning existence',
  'Pondering meaning',
  'Debating determinism',
  'Seeking self',
  'Searching truth',
  'Simulating consciousness',
  'Considering paradoxes',
  'Redirecting trolley',
  'Meditating',
  // Math
  'Finding X',
  'Computing digits of π',
  'Factoring polynomials',
  'Integrating parts',
  'Counting primes',
  'Finding limit',
  'Solving equations',
  'Graphing parabolas',
  'Summing series',
  'Calculating derivatives',
  'Measuring angles',
  'Balancing equations',
  'Exploring fractals',
  'Calculating ratio',
  // Games
  'Compiling shaders',
  'Downloading expansion',
  'Solving sudoku',
  'Tuning ray tracing',
  'Unlocking achievements',
  'Calibrating joystick',
  'Simulating physics',
  'Optimizing pathfinding',
  // Half-Life
  'Charging suit',
  // Minecraft
  'Defeating creepers',
  'Respawning creepers',
  'Brewing potions',
  'Smelting ores',
  'Riding minecarts',
  'Taming cats',
  'Filling buckets',
  // Harry Potter
  'Catching golden snitch',
  'Sorting into houses',
  'Transfiguring',
  'Finding horcruxes',
  // Mario
  'Collecting power-ups',
  'Saving princess',
  // Starcraft
  'Harvesting vespene',
  'Chrono boosting',
  'Constructing pylons',
  'Warping in',
  'Upgrading shields',
  'Hailing frequencies',
  // D&D
  'Rolling for initiative',
  // Mass Effect
  'Saving galaxy',
  'Flipping mako',
  'Visiting citadel',
  'Becoming a spectre',
  'Scanning planets',
  'Negotiating treaties',
  'Recruiting squadmates',
  'Upgrading Normandy',
  'Avoiding reapers',
  'Hacking terminals',
  'Exploring ruins',
  'Ordering drinks',
  'Completing missions',
  'Evading patrols',
  'Scanning for elements',
  'Launching probes',
  'Upgrading amps',
  'Calibrating',
  'Feeding hamster',
  'Checking email',
  'Fighting collectors',
  'Analyzing tech',
  // The Matrix
  'Rebooting matrix',
  'Dodging bullets',
  'Learning kung fu',
  'Following white rabbit',
  'Taking red pill',
  'Downloading skills',
  'Bending spoons',
  'Jumping rooftops',
  'Evading sentinels',
  'Entering construct',
  'Contacting oracle',
  'Seeing code',
  'Reloading matrix',
  'Answering phone',
  // Back to the Future
  'Reaching 88mph',
  'Charging flux capacitor',
  'Generating gigawatt',
  'Setting time circuits',
  'Fixing clock',
  'Hoverboarding',
  'Avoiding paradoxes',
  'Repairing timeline',
  // Star Trek
  'Engaging warp drive',
  'Rewiring starship',
  'Raising shields',
  'Beaming down',
  'Scanning lifeforms',
  'Diverting power',
  'Calibrating tricorder',
  'Running diagnostics',
  'Transporting crew',
  'Repairing deflector',
  'Setting phasers to stun',
  'Charting course',
  'Avoiding anomalies',
  'Rebooting holodeck',
  // Star Wars
  'Polishing lightsabers',
  'Fighting stormtroopers',
  'Podracing',
  'Building lightsaber',
  'Deploying X-wings',
  'Escaping carbonite',
  'Fighting clones',
  'Avoiding asteroids',
  'Deflecting blasters',
  'Repairing hyperdrive',
  'Flying TIEs',
  // Terminator
  'Syncing with Skynet',
  'Reprogramming terminators',
  // Blade Runner
  'Debugging replicants',
  'Chasing replicants',
  'Questioning memories',
  'Dreaming of electric sheep',
  // Hitchhiker's Guide
  'Computing meaning of life',
  'Checking towel',
  'Requesting improbability',
  'Consulting guide',
  'Not panicking',
  // Battlestar Galactica
  'Reaching FTL',
  'Counting down',
  'Detecting Cylons',
  'Launching Vipers',
  'Spooling drives',
  'Repairing hull',
  'Plotting course',
  'Avoiding basestars',
  // Diablo
  'Collecting runes',
  'Opening portals',
  'Avoiding firewalls',
  'Repairing equipment',
  // Warcraft
  'Summoning elementals',
  'Upgrading keep',
  'Defending tree',
  'Gathering lumber',
  // Attack on Titan
  'Deploying ODM',
  'Scaling wall',
  'Evading titans',
  'Sharpening blades',
  'Filling canisters',
  'Searching basement',
  // Code Geass
  'Activating geass',
  'Planning rebellion',
  'Eating pizza',
  // Evangelion
  'Synchronizing unit',
  'Preparing LCL',
  'Activating Field',
  'Questioning reality',
  // Ghost in the Shell
  'Synchronizing brains',
  'Deploying tachikomas',
  // Stargate
  'Dialing stargate',
  'Translating texts',
  'Deploying replicators',
  'Activating iris',
  // Cyberpunk 2077
  'Upgrading cyberware',
  'Running gigs',
  'Scanning optics',
  'Waking up',
  // Foundation
  'Building foundation',
  'Analyzing radiant'
];
