# https://prettier.io/docs/en/configuration.html
arrowParens: avoid
endOfLine: lf
trailingComma: none
tabWidth: 2
plugins:
  - '@prettier/plugin-ruby'
  - '@shopify/prettier-plugin-liquid'
semi: true
singleQuote: true
overrides:
  - files:
      - ./_includes/*.html
      - ./_layouts/*.html
    options:
      parser: liquid-html
