# Site settings
title: ArchiDep
email: contact@archidep.ch
description: >-
  Media engineering architecture and deployment course
baseurl: ''
url: 'https://archidep.ch'
port: 42001
livereload_port: 42002
livereload_base_url: http://localhost:42002
livereload_script_forced: false
destination: '../app/priv/static'
strict_front_matter: true

collections:
  cheatsheets:
    order:
      - command-line/cheatsheet.md
      - git/cheatsheet.md
      - sysadmin/cheatsheet.md
    output: true
  course:
    output: true
  json:
    output: true
  notices:
    output: true
  progress:
    output: true

collections_dir: collections

# Build settings
plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-toc
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - .editorconfig
  - package.json
  - package-lock.json
  - pdf/
  - scripts/
  - src/
  - tsconfig.json
  - tsconfig.assets.json
  - tsconfig.scripts.json
  - webpack.config.cjs

keep_files:
  - assets
  - cache_manifest.json
