source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"

# HTML parsing
gem "nokogiri", "~> 1.18"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag", "~> 2.7"
  gem "jekyll-target-blank", "~> 2.0"
  gem "jekyll-toc", "~> 0.19.0"
  gem "jemoji", "~> 0.13.0"
end

group :development do
  gem "prettier_print", "~> 1.2"
  gem "syntax_tree", "~> 6.3"
  gem "syntax_tree-haml", "~> 4.0"
  gem "syntax_tree-rbs", "~> 1.0"
end
