#!/usr/bin/env bash
set -e

config_dir="/etc/archidep"
server_id_file="${config_dir}/server-id"
token_file="${config_dir}/token"

server_id="$(head -n 1 "${server_id_file}")"
token="$(head -n 1 "${token_file}")"

curl -vv -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  "{{api_base_url}}/callbacks/servers/${server_id}/up"
